spring:
  application:
    name: ocivault
  cloud:
    oci:
      config:
        type: file
        profile: ${PROFILE}
      region:
        static: ${REGION}
      vault:
        compartment: ${COMPARTMENT_OCID}
        vault-id: ${VAULT_OCID}
        enabled: true
        property-refresh-interval: 10000ms
        property-sources:
        - vault-id: ${VAULT_OCID}